[features]
seeds = false
skip-lint = false

[programs.mainnet]
bonkr = "BonkrTokenLaunchpad1111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
